### ISSUE TITLE
Password Cleartext

### ISSUE THREAD

**Issue by nealhead** [turboblack/HamsterCMS#3]
Are there any considerations on security when having the username and password stored in clear text in the admin.php file?

**Comment by turboblack** [comment]
since the file cannot be read from the outside - this is not a problem, especially since there is no attachment to the engine, you do not have to keep this file on the hosting, it is only for editing the contents.
after finishing editing, this file can be deleted
you can also rename it as you like, this also does not affect the functionality

**Comment by ZX-Commodore-ST** [comment]
I'm not into FUD at all but marking it as completed? Expecting users to delete and reupload admin.php file on every site edit? You cannot be serious! Should be fixed ASAP.

Even if it's only some login details I still don't want anyone else to be able to read my passwords and web1.0hosting.net admin might already be able to read them all. What if their server gets hacked? As much as I can have sentiment for 30 year old look I don't think it's good to approach internet security with mindset from early 90s.
